spring:
  profiles:
    active: dev

  application:
    name: server-eureka

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

    registerWithEureka: false
    fetchRegistry: false
