spring:
  profiles:
    active: dev

  application:
    name: server-member

  jpa:
    open-in-view: false

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
